### PR TITLE
Minor coding style fixes and unit tests

### PR DESCRIPTION
**Pull request by sunn-e**
Hi, I'm Sunny. One of the GCI-2019 mentor for R Project. I have decided to participate in GSoC this year as a student. 
I thought this is pretty cool as you are trying to streamline the whole project. I have played with the docker,CIs too so I guess that is pretty doable. And ofcourse , I have worked with R for my undergrad Math courses so that should not be a hurdle. I'm not any expert but I'm confident enough to build things on my own.

As part of the test, mentioned on the ideas page, I went ahead and 

- cloned the project locally.
- Setup development environment (Using Windows 10 for time being, I have dual boot with Ubuntu 16)
- Installed dependencies
- Installed lintr to quickly check what is broken in the package. Doing `linter("common_functions.R")`point  suggested me to fix few code style warnings and better function for length, `length()` to `seq_len()` for example. I removed some redundant spaces too.
- I had no idea how to create any advanced tests so I simply created a `/test` folder, created a simplt `test_common_functions` . Added simple unit tests to check is.na. Ran `testthat::test_dir("tests")`.  
- There are some changes in doc name too to reflect the changes on the whole package. That should not be a problem.

That's it for now. I'm looking into other tests too. 
I'm into R-Project mentors list so you can mail me on sunnydhoke22[at]gmail[dot]com too.
Looking forward to working with you guys this summer. Ciao.

### CODE REVIEW

**Comment by sunn-e** [comment]
Also, It would be very cool if you can send me your paper about the bdverse @thiloshon @PoGibas @tom-gu @vijaybarve 
>sunnydhoke22[at]gmail[dot]com

**Comment by thiloshon** [comment]
Changing exported function signatures will break downstream packages. Holding merge till we are ready for verse-level refactoring.

**Review by thiloshon — COMMENTED** [review]
Holding till r-opensci submission. Please follow the updated Pull Request template.

**Comment by sunn-e** [comment]
> 
> 
> Changing exported function signatures will break downstream packages. Holding merge till we are ready for verse-level refactoring.

I sent this PR just as a demonstration. Thanks for the feedback.




> 
> 
> Holding till r-opensci submission. Please follow the updated Pull Request template.

All right. Tomer has already told me about the  r-opensci submission.  I will send PR with new template very soon.
Thanks @thiloshon

**Comment by PoGibas** [comment]
`length` replacement with `seq_len` should not work, please check `1:seq_len(names(mtcars))`

**Comment by PoGibas** [comment]
It's a bad practice to source code during testing (eg. `source("../R/common_functions.R", chdir = TRUE)`), please check how it's done in other `bdverse` packages

**Comment by sunn-e** [comment]
> 
> 
> `length` replacement with `seq_len` should not work, please check `1:seq_len(names(mtcars))`

All right. I think  I should not rely too much on what lintr says.  I will keep that in mind.



> 
> 
> It's a bad practice to source code during testing (eg. `source("../R/common_functions.R", chdir = TRUE)`), please check how it's done in other `bdverse` packages

I will surely look into it. Thanks a lot @PoGibas . I have a lot to learn from you guys.

**Comment by sunn-e** [comment]
> 
> 
> I would suggest to replace such logic with `%in%`

Hi, I found out testthat assumes context by the file name. So a file named test_example.R will be used by testthat to check example.R . We need not define anything specifically.

**Comment by sunn-e** [comment]
>Use of context() is no longer recommend. Instead omit it, and messages will use the name of the file instead. This ensures that the context and test file name are always in sync.

**Comment by damodardhakad** [comment]
Hello @sunn-e and others, I am preparing for this year's GSoC with the R project.  And I need to submit a PR with two unit tests for summarizeDataframe and return_core functions. But It seems there are already two pull requests available for these test cases. May I take your work from here or start from scratch.

**Comment by vijaybarve** [comment]
@damodardhakad Welcome to bdverse. What project tests are you trying to complete?

**Comment by damodardhakad** [comment]
Hello @vijaybarve,

I am preparing for "[Agile app development via bdtools](https://github.com/rstats-gsoc/gsoc2021/wiki/bdtools)" project listed on R GSoC -21 wiki. 
My first task is to - "[fork the bdutilities package, develop two unit tests, and submit a PR](https://github.com/rstats-gsoc/gsoc2021/wiki/bdtools#tests)". so I fork the bdutilities repository. locally Build and install it. 
Looking at bdutilities/R/common_functions.R and bdutilities/R/bdutilities.R, it seems that the two functions need testing 1. summarizeDataframe and 2. return_core. 

Am I thinking in the right direction? I am still at an early stage but want to complete the first task soon. For writing test cases I am following [this](https://towardsdatascience.com/unit-testing-in-r-68ab9cc8d211) tutorial available on towardsdatascience.com

**Comment by tom-gu** [comment]
Hi @damodardhakad 
Yes, you're on the right track.

To learn about testing, you can also use:
- https://testthat.r-lib.org/index.html 
- https://r-pkgs.org/tests.html

**Comment by damodardhakad** [comment]
Thanks @tom-gu I tried writing some basic tests and also get success. I will try to soon complete all tasks listed on the R GSoC wiki.

**Pull request closed without merging**
